In [24]:
import numpy as np
import pandas as pd


people_df = pd.read_csv("data/people.csv")

In [21]:
people_df.head()

,personId:ID(Person-ID),first_name,last_name,birth_date:date,age:int,location,genre,bot_score:float,:LABEL
995,b278b907-a893-4c88-9f1f-f05b26d4ede1,Jean,Walter,1919-04-10,105,Toledo New York US,Cars and automobiles,0.94,person
996,a6e7a09a-1258-46f0-bc87-3fb1149a338a,Thomas,Williams,1955-10-12,69,Rolla Chicago US,Fitness,0.62,person
997,e5d2b34d-3b55-43d5-bc79-3bdaff5b6a24,Anthony,Smith,1929-08-27,95,Woodlawn New York US,Art,0.98,person
998,ee003e9d-3b90-4aea-b511-8d57c0d76f41,Sara,Jenkins,2011-12-27,13,Collinwood New York US,Science,0.93,person
999,1d81b320-8c78-4a94-ba01-9f93c35bd622,Katherine,Snow,1980-02-07,44,Pekin Chicago US,Fitness,0.99,person

In [23]:
people_df.tail()

,personId:ID(Person-ID),first_name,last_name,birth_date:date,age:int,location,genre,bot_score:float,:LABEL
995,b278b907-a893-4c88-9f1f-f05b26d4ede1,Jean,Walter,1919-04-10,105,Toledo New York US,Cars and automobiles,0.94,person
996,a6e7a09a-1258-46f0-bc87-3fb1149a338a,Thomas,Williams,1955-10-12,69,Rolla Chicago US,Fitness,0.62,person
997,e5d2b34d-3b55-43d5-bc79-3bdaff5b6a24,Anthony,Smith,1929-08-27,95,Woodlawn New York US,Art,0.98,person
998,ee003e9d-3b90-4aea-b511-8d57c0d76f41,Sara,Jenkins,2011-12-27,13,Collinwood New York US,Science,0.93,person
999,1d81b320-8c78-4a94-ba01-9f93c35bd622,Katherine,Snow,1980-02-07,44,Pekin Chicago US,Fitness,0.99,person

In [29]:
people_df[10:20]

,personId:ID(Person-ID),first_name,last_name,birth_date:date,age:int,location,genre,bot_score:float,:LABEL
10,01b180f0-1c3a-465a-8f98-59ae0d3fc6a1,Brian,Schultz,1966-03-09,58,Ada Chicago US,Health and wellness,0.10,person
11,ce4552d1-935b-4996-8fa0-53531080c25a,Amy,Wilkins,1960-10-21,64,Carlsbad Denver US,DIY and crafts,0.24,person
12,5709ae8c-ca41-46ac-a62d-59b6ccb19ee4,Laura,Williams,2013-09-15,11,Nutley New York US,Science,0.13,person
13,7d299334-a56d-4fc0-bdc1-91caccf00edc,Anthony,Ryan,1962-08-22,62,Carlsbad Denver US,Technology,0.26,person
14,1a86b6ec-2539-4097-b1d3-590a92fbec9d,Daniel,Davis,1965-12-03,59,North Lauderdale New York US,DIY and crafts,0.68,person
15,1584b301-0382-4ba2-b4fe-712b872005fd,Candice,Hardy,1999-03-24,25,Lino Lakes Chicago US,Nature,0.91,person
16,4c763328-d320-49fb-997f-2694e4b27730,David,Gordon,1955-07-05,69,Palestine Chicago US,Pets,0.92,person
17,a5e77001-7b9b-418c-86b4-26205630ae10,Timothy,May,1947-08-06,77,Middle River New York US,Gardening,0.60,person
18,d1274f87-75d1-4c60-82ac-76b7a1c8ab6e,Anna,Herrera,1980-04-21,44,Camarillo Los Angeles US,Books,0.25,person
19,65a2d033-489c-4836-8373-c81b80e7caf8,James,Swanson,1919-07-20,105,Indio Los Angeles US,DIY and crafts,0.42,person

In [30]:
people1_df = people_df[["first_name", "last_name", "genre"]][:500] # first 500 people
people2_df = people_df[["first_name", "last_name", "genre"]][500:] # last 500 people

In [31]:
people1_df.merge(people2_df, how="inner", left_on="genre", right_on="genre")

     first_name_x last_name_x  genre first_name_y last_name_y
0            Mark      Fields  Music        Kylie       Moore
1            Mark      Fields  Music      Timothy      Holmes
2            Mark      Fields  Music         Luke     Carlson
3            Mark      Fields  Music       Leslie      Fields
4            Mark      Fields  Music       Steven     Kennedy
...           ...         ...    ...          ...         ...
8480    Elizabeth      Miller  Books      Kaitlin       Brown
8481    Elizabeth      Miller  Books        Sarah        Mayo
8482    Elizabeth      Miller  Books    Cassandra        Hess
8483    Elizabeth      Miller  Books        James     Herring
8484    Elizabeth      Miller  Books        Faith       White

[8485 rows x 5 columns]

In [39]:
people_df[people_df["location"] == "Rolla Chicago US"]

,personId:ID(Person-ID),first_name,last_name,birth_date:date,age:int,location,genre,bot_score:float,:LABEL
89,f9614ee7-c774-4428-a2d1-6bad9d5afbe1,Brandy,Willis,1947-08-09,77,Rolla Chicago US,Technology,0.28,person
116,454632f2-755a-43e9-965e-4adb05cd291e,Kayla,Blanchard,1927-10-07,97,Rolla Chicago US,History,0.29,person
175,9a8934eb-205d-49f0-bffc-a888109c384b,Ronald,Terrell,1925-03-11,99,Rolla Chicago US,Art,0.40,person
183,d36fa40e-4214-46ea-a8d2-2f94344de2fd,Tracy,Henry,1988-09-27,36,Rolla Chicago US,Parenting and family,0.34,person
226,35a1743b-9019-453d-b59b-4be7bfe9eb0f,Joshua,Hill,1951-12-29,73,Rolla Chicago US,Nature,0.10,person
507,b9020c4d-1a7d-4a02-ab28-1d07b0cbaadb,Tommy,Miller,2003-10-03,21,Rolla Chicago US,Books,0.54,person
536,7409c4ae-3dd4-4ab1-acb0-bd704aa43da5,Rhonda,Cline,2021-03-14,3,Rolla Chicago US,Outdoor activities,0.51,person
637,4b026e90-d57f-475d-9d20-5c8c8bd35d43,Brittany,French,2006-11-28,18,Rolla Chicago US,Parenting and family,0.19,person
676,5aa00d04-d6a2-49ab-b066-0ab8128cc4e5,Susan,Bishop,1961-01-19,63,Rolla Chicago US,Gaming,0.99,person
719,90a3cf5b-ec60-427d-ad50-7e399bcab1c3,Megan,Stephens,2013-09-06,11,Rolla Chicago US,Health and wellness,0.55,person
909,d863928e-1ada-49aa-a45d-f89dd764881c,Kathy,Roth,1939-04-07,85,Rolla Chicago US,Art,0.37,person
950,1cd6cb88-00f5-4432-a369-3bf689935e0d,Ashlee,Phillips,1921-02-26,103,Rolla Chicago US,Cars and automobiles,0.75,person
982,20ac475d-8830-4df5-8f06-8b9eabfcfc53,Kendra,Wallace,1952-04-28,72,Rolla Chicago US,Travel,0.90,person
996,a6e7a09a-1258-46f0-bc87-3fb1149a338a,Thomas,Williams,1955-10-12,69,Rolla Chicago US,Fitness,0.62,person